config/routes.rb
Rails.application.routes.draw do
  devise_for :users

#   devise_for :users do
#   get '/users/sign_out' => 'devise/sessions#destroy'
# end
  resources :schools

  root to: "schools#new"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/school.rb
class School < ApplicationRecord
	# validates :SCHOOLNAME, length: {minimum:5, maximum:20}
	# validates :ADDRESS, length: {minimum:10, maximum:20}
	# validates :CITY, length: {maximum:10}
	# validates :STATE, length: {maximum:15, minimum:5},numericality: { only_integer: false }
	# validates :PINCODE, numericality: { only_integer: true }
	# # validates :PINCODE,length: { maximum: 6 }
	# validates :AFFILIATEDBOARD,  presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    protect_from_forgery with: :exception

      

	  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
  protect_from_forgery with: :exception
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:SCHOOLNAME, :ADDRESS, :CITY, :STATE, :PINCODE, :AFFILIATEDBOARD)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Screens</title>
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header>
    <div class="container-fluid">
      <div class="logo-part">
        <img alt="Brand" src="/assets/Skala-icon.png"> 
        <%= link_to image_tag("settings.svg", class: 'a'), destroy_user_session_path, method: :delete %>
     <!--   <a rel="nofollow" data-method="delete" href="/users/sign_out">
       <img class="a" src="/assets/settings-b77eec5b75a761f9861fed4e04c9f6a680c907f45f5f96d71c87755118a124d3.svg" alt="Settings"></a>
        </div> -->
    </div>
  </header>

  <div class="navbar">
      <ul class="">
      <li><img alt="Brand" src="/assets/male3.svg"> <a href="/users/sign_up">User Management Portal</a></li>
      <li><img alt="Brand" src="/assets/cash-register.svg"><a href="/register_schools/new">Registration Portal</a></li>
      <li><img alt="Brand" src="/assets/controls.svg"> <a href="/register_schools/new">Content Portal</a></li> 
    </ul>
  </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

<!--   <header>
  <div class="background_image">

  </div>
</header>

  <nav class = "navbar navbar-default" id = "nav" role = "navigation">
   
   <div class = "navbar-header">
      <a class = "navbar-brand" href = "#">User Management Portal</a>
   </div>
   
   <div>
      <p class = "navbar-text navbar-right">
         
         <a href = "#" class = "navbar-brand">Content Portal</a>
      </p>
   </div>
   
</nav> -->
<!-- <img src="maxresdefault.jpg" alt="Paris" width="400" height="300"> -->
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin Screens</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/schools/_form.html.erb
<%= form_for(school) do |f| %>
  <% if school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :SCHOOLNAME, class:"label" %>
    <%= f.text_field :SCHOOLNAME , class:"input"%>
  </div>

  <div class="field">
    <%= f.label :ADDRESS, class:"label" %>
    <%= f.text_area :ADDRESS, class:"input" %>
  </div>

  <div class="field">
    <%= f.label :CITY ,class:"label" %>
    <%= f.text_field :CITY, class:"input" %>
  </div>

  <div class="field">
    <%= f.label :STATE ,class:"label" %>
    <%= f.text_field :STATE, class:"input" %>
  </div>

  <div class="field">
    <%= f.label :PINCODE ,class:"label"%>
    <%= f.text_area :PINCODE, class:"input" %>
  </div>


 <!--    <div>
  <p>
  <b>AFFILIATEDBOARD</b><br /><br />
    <%= f.radio_button :AFFILIATEDBOARD, 'CBSE', class:"aa" %>
     <%= f.label :AFFILIATEDBOARD, 'CBSE', :value => 'CBSE', class:"radio" %>
    <%= f.radio_button :AFFILIATEDBOARD, 'ICSE',  class:"aa" %>
      <%= label :AFFILIATEDBOARD, 'ICSE', class: "radio" %>
    <%= f.radio_button :AFFILIATEDBOARD, 'Matric', class: "aa" %>
     <%= label :AFFILIATEDBOARD, 'Matric', class: "radio" %>
    <%= f.radio_button :AFFILIATEDBOARD, 'State Board',  class:"aa" %>
     <%= label :AFFILIATEDBOARD, 'State Board', class: "radio " %>
    </p>
  </div> -->

  <div>

    <label>
       AFFILIATEDBOARD
    </label>

     <label >
      <%= f.radio_button :AFFILIATEDBOARD, 'CBSE' %><span>CBSE</span>
    </label>

    <label>
      <%= f.radio_button :AFFILIATEDBOARD, 'ICSE' %><span>ICSE</span>
    </label>

    <label>
    <%= f.radio_button :AFFILIATEDBOARD, 'Matric' %><span>Matric</span>  
    </label>

    <label>
           <%= f.radio_button :AFFILIATEDBOARD, 'State Board' %><span>StateBoard</span>
    </label>
    
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1 class="edit">EDITING SCHOOL DETAILS</h1>

<%= render 'form', school: @school %>

<div class="w3-btn-group w3-show-inline-block">
  <button class="w3-btn">
      <%= link_to 'SHOW', @school %>
  </button>
  <button class="w3-btn w3-teal">
       <%= link_to 'BACK', schools_path %>
  </button>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="color">LIST OF SCHOOLS</h1><br>

<table class="table table-hover">
  <thead>
    <tr>
      <th>SCHOOL NAME</th>
      <th>ADDRESS</th>
      <th>CITY</th>
      <th>STATE</th>
      <th>PINCODE</th>
      <th>AFFILIATED BOARD</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.SCHOOLNAME %></td>
        <td><%= school.ADDRESS %></td>
        <td><%= school.CITY %></td>
        <td><%= school.STATE %></td>
        <td><%= school.PINCODE %></td>
        <td><%= school.AFFILIATEDBOARD %></td>
        <td><%= link_to 'EDIT', edit_school_path(school) %></td>
       <!--  <td><%= link_to 'DESTROY', school, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        <!-- <td><%= link_to 'Show', school %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button class="button"><%= link_to 'CREATE SCHOOL', new_school_path %></button>

app/views/schools/new.html.erb
<h1 class="new">NEW SCHOOL</h1>

<%= render 'form', school: @school %>

<!-- <button class="w3-btn w3-white w3-border w3-border-blue w3-round-xlarge"><%= link_to 'BACK', schools_path %></button> -->
<%= link_to image_tag("backicon.png", width:"50px", height: "50px"), schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>
<h1 class="show">SCHOOL DETAILS</h1>

<p class="p">
  <strong>SCHOOL NAME:</strong>
  <%= @school.SCHOOLNAME %>
</p>

<p class="p">
  <strong>ADDRESS:</strong>
  <%= @school.ADDRESS %>
</p>

<p class="p">
  <strong>CITY:</strong>
  <%= @school.CITY %>
</p>

<p class="p">
  <strong>STATE:</strong>
  <%= @school.STATE %>
</p>

<p class="p">
  <strong>PINCODE:</strong>
  <%= @school.PINCODE %>
</p>

<p class="p">
  <strong>AFFILIATED BOARD</strong>
  <%= @school.AFFILIATEDBOARD %>
</p>

<div class="w3-btn-bar w3-border">
  <button class="w3-btn"><%= link_to 'EDIT', edit_school_path(@school) %>
  </button>

  <button class="w3-btn"><%= link_to 'BACK', schools_path %></button>
</div>